best_trip_user:
    resource: "@BestTripUserBundle/Resources/config/routing.yml"
    prefix:   /

best_trip_mail:
    resource: "@BestTripMailBundle/Resources/config/routing.yml"
    prefix:   /

best_trip_graphe:
    resource: "@BestTripGrapheBundle/Resources/config/routing.yml"
    prefix:   /Graphe

best_trip_wee_go:
    resource: "@BestTripWeeGoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 
